### ISSUE TITLE
[Feature Request] Message TextView

### ISSUE THREAD

**Issue by toshi0383** [TakuSemba/Spotlight#100]
I'm currently working on this on my own fork.
If you'd like it, I can make it into a PR.

![Screenshot_1598932860](https://user-images.githubusercontent.com/6007952/91793874-6b4f7980-ec54-11ea-9e26-37ac381a1d58.png)

Inspired by https://github.com/ephread/Instructions

**Comment by TakuSemba** [comment]
Thank you for creating the issue.

While it's a nice layout, I'm not thinking about adding it to Spotlight for now since it's still archivable using `Target.Builder.setOverlay(layout)` with whatever layout you would like.

**Comment by toshi0383** [comment]
Thanks for your response.

I would say, requiring fine-grained Overlay configuration for each time can be cumbersome for us developers. Especially for Individual developers, who don't usually have much time spending layout for Tutorials.
It's like "I give you this target view. Give user a heads-up with this message" thing. I mean, it can be simpler.

I understand that there is no solution to fit in all use case, so maybe we can provide low-level API (which current Spotlight does) and also high-level API like my suggestion.
Thoughts? Please look at what https://github.com/ephread/Instructions does, too. To me it covers most of simple use case with a lot of UI options.

Please keep in mind that It's completely fine to reject this proposal. Because in that case, I will just come up with my own library or something.
Thanks a lot though. I've learned a lot from your code anyways!😉
