### ISSUE TITLE
Add ability to set background color as int

### ISSUE THREAD

**Issue by Albul** [TakuSemba/Spotlight#107]
I have resolved colors in runtime, due to light/black themes in the app. This colors is set to activity theme by attributes. So I need to set background color of `Spotlight` as int. 
Also it suggest to make api more consistent, as FlickerEffect, and RippleEffect takes color as int. It would be more consistent when `Spotlight.Builder.setBackgroundColor` would take int and `Spotlight.Builder.setBackgroundColor` take an resource to color.
Or to keep backward compatibility you just could add `Spotlight.Builder.setBackgroundColorInt` method.

**Comment by Albul** [comment]
@TakuSemba 
First suggestion is implemented in this pull request
https://github.com/TakuSemba/Spotlight/pull/108

**Comment by TakuSemba** [comment]
I'm closing this issue since the PR was merged.

Thank you @Albul !
