### ISSUE TITLE
Set click listener only in spotlight

### ISSUE THREAD

**Issue by putrapurba** [TakuSemba/Spotlight#11]
hi there, i want to implement on click only on spotlight so i can say it cant cancellable on when user touch on black area. Is this feature already implemented? or is there any code to backup this logic?

thank you

**Comment by TakuSemba** [comment]
thank you for the issue, the answer is unfortunately, no.
there is no way to do so.

**Comment by TakuSemba** [comment]
I added this functionality on version 1.3.0. check it out.

**Comment by RobertoAlvarezCeballos** [comment]
Sorry to reopen this but how exactly you listen only to the spotlight? I can´t see it.
