### ISSUE TITLE
Please publish to something other than jCenter. 

### ISSUE THREAD

**Issue by farkerhaiku** [TakuSemba/Spotlight#115]
jCenter is shutting down May 1st. 

See this article for details: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by GuilhE** [comment]
One thing you can do, for now, is to manually sync to MavenCentral (setup OSS [account](https://oss.sonatype.org/#welcome)) through Bintray console. It's a quick fix and latter on you can update the gradle script :)

[This](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/) may also help.

**Comment by GuilhE** [comment]
Another nice helping article: [Migrating old artifacts from JCenter to MavenCentral](https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/)

**Comment by TakuSemba** [comment]
Thanks for the issue. Yes, I'm on it. I will get it done by March.

**Comment by TakuSemba** [comment]
@farkerhaiku @GuilhE 
I put all of the artifacts on MavenCentral as well.
I still have some on my plate for this but now you can use MavenCentral to use this library.

**Comment by GuilhE** [comment]
@TakuSemba thanks! 🙏
