### ISSUE TITLE
Spotlight Always on Corner point

### ISSUE THREAD

**Issue by Radmanfar** [TakuSemba/Spotlight#12]
i use spotlight same the sample
but in my project , spotlight always show in corner
<a href="http://uupload.ir/view/nuly_screenshot_1513489353.png" target="_blank"><img src="http://uupload.ir/files/nuly_screenshot_1513489353_thumb.png" border="0" alt="آپلود عکس" /></a>

<a href="http://uupload.ir/view/4na2_screenshot_1513489297.png" target="_blank"><img src="http://uupload.ir/files/4na2_screenshot_1513489297_thumb.png" border="0" alt="آپلود عکس" /></a>

**Comment by RagavendraM** [comment]
@Radmanfar I'm also facing issue. I checked to take view StartPosition its (0,0) thats y its showing Top left Corner.

**Comment by TakuSemba** [comment]
can you tell me what device are you using?

**Comment by josephmangmang** [comment]
Same issue when using here. i'm using setPoint(view)

**Comment by TakuSemba** [comment]
OK, I'll look into it.
Is there any conditions? Does that happen always or on any specific devices???

**Comment by josephmangmang** [comment]
I see. It only happens when you want to show spotlight immediately. Didn't notice there's `addOnGlobalLayoutListener`  on the Usage.  But I fixed it using 
```
view.post(new Runnable(){
    public void run(){
         Spotlight.with(this)...start();
    }
});
```

**Comment by TakuSemba** [comment]
yea, thanks!

**Comment by abdelrahmana** [comment]
in kotlin 
 constrainLayout.post {
            setSpotLight()
        }
 // so the constrainlayout is the rootlayout view and the function of setSpotLight is the function of 
declaration and definition of spotlight and targets
