### ISSUE TITLE
Coach mark on Menu items of BottomNavigation 

### ISSUE THREAD

**Issue by hrishibargal** [TakuSemba/Spotlight#132]
I am trying to show a coach mark on BottomNavigation's menu item but am not able to achieve it.
though I can show the coach mark on BottomNavigation as it is a View but not able to show specific menu items on BottomNavigation.

I tried menu item casting to view  but getting an exception like "java.lang.ClassCastException: androidx.appcompat.view.menu.MenuItemImpl cannot be cast to android.view.View"

**Comment by cmy82** [comment]
When setting the view as the target, it is just to get the screen coordinates. You can use other means to find the coordinates of the menu item, or just set a static location for the spotlight target.

**Comment by hrishibargal** [comment]
I could resolved this using co ordinates
