### ISSUE TITLE
can't set alpha?

### ISSUE THREAD

**Issue by LongAgoLong** [TakuSemba/Spotlight#14]
it's always in zero to one, can you provide method to set zero to 0.x?

**Comment by maherhanafi** [comment]
@LongAgoLong I created a Pull Request to let user define the color they want for the overlay.
I hope @TakuSemba will review and accept this to be merged

**Comment by TakuSemba** [comment]
thanks, i will check @maherhanafi

**Comment by TakuSemba** [comment]
I released a new version which supports background overlay color. 👍
