### ISSUE TITLE
com.takusemba.spotlight.SpotlightView.turnDown(float, long, android.animation.TimeInterpolator)' on a null object reference

### ISSUE THREAD

**Issue by laozhao1005** [TakuSemba/Spotlight#16]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.takusemba.spotlight.SpotlightView.turnDown(float, long, android.animation.TimeInterpolator)' on a null object reference

**Comment by TakuSemba** [comment]
could you give me a details? 
any conditions?

**Comment by ghataa** [comment]
Same here. I opened a pull request with a fix: https://github.com/TakuSemba/Spotlight/pull/54
