### ISSUE TITLE
round rectangle spotlight

### ISSUE THREAD

**Issue by mickychen0524** [TakuSemba/Spotlight#18]
Thanks for awesome library, but I am little disappointed that there is no round rectangle option.
anyone who forked and made changes for this feature?

**Comment by TakuSemba** [comment]
sorry for that.
im thinking to add that feature next.

**Comment by mickychen0524** [comment]
@TakuSemba Thanks, What is eta for release new version?
Have you ever considered of custom position for title/message in the relative margin of spotlight view?

**Comment by TakuSemba** [comment]
I havent decided when to release next version, but pull requests are welcome.

> Have you ever considered of custom position for title/message in the relative margin of spotlight view?

no, but it sounds good to add that function.

**Comment by TakuSemba** [comment]
at the version of 1.5.0, i added the custom shape feature.
now, you can draw your own shape implementing Shape.java

```java
public class RoundRectangle implements Shape {

    private float width;
    private float height;

    public RoundRectangle(float width, float height) {
        this.width = width;
        this.height = height;
    }

    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        // draw your shape using canvas.
    }
    ...
}
```

```
CustomTarget customTarget = new CustomTarget.Builder(this)
    .setShape(new RoundRectangle(200f, 150f))
    ...
    .build();
```

**Comment by mickychen0524** [comment]
@TakuSemba Great, Thanks for your update. How's custom position for title and message?

**Comment by TakuSemba** [comment]
you can set the position for the target

```java
SimpleTarget simpleTarget = new SimpleTarget.Builder(this)
    .setPoint(100f, 340f)
    ...
    .build();
```

and if you use the `CustomTarget.java` you can set any layout for the overlay.
