### ISSUE TITLE
Is this works with fragments too?

### ISSUE THREAD

**Issue by priyanshu2112** [TakuSemba/Spotlight#21]

**Comment by TakuSemba** [comment]
I think it works, doesnt it?

**Comment by priyanshu2112** [comment]
Sorry, I got my problem.
and after that I wanna know how to work with Spotlight with RecyclerView?

**Comment by TakuSemba** [comment]
I doesnt matter which view you use. you can just pass the view or rect or any thing to a target.

**Comment by mitsest** [comment]
Does it work with a view pager that contains fragments?
