### ISSUE TITLE
target.getView().getTag() return Null in OnTargetStateChangedListener

### ISSUE THREAD

**Issue by dhinx** [TakuSemba/Spotlight#25]
Hello,
I got trouble when put data in tag view before put in setPoint method and get data in OnTargetStateChangedListener in method onStarted and onEnded, and always got null value.

I think this is a bug.

Sorry, my english is bad.

Thank you

**Comment by TakuSemba** [comment]
Ok, I'll look into it. 
can you share the code how you put the data in tag?

**Comment by dhinx** [comment]
i'm sorry for late response.

this is my code

Call methods :
```
helpdeskButton.setTag(UpdateHistory.Feature.HELPDESK);

SimpleTarget target = Util.generateTarget(DashboardActivity.this, helpdeskButton, getString(R.string.helpdesk_title), getString(R.string.helpdesk_description));
Util.showSpotLights(DashboardActivity.this, target);
```

Generate Target Method :
```
public static SimpleTarget generateTarget(Activity activity, View point, String title, String description) {
    return new SimpleTarget.Builder(activity)
        .setPoint(point)
        .setRadius(80f)
        .setTitle(title)
        .setDescription(description)
        .setOnSpotlightStartedListener(new OnTargetStateChangedListener<SimpleTarget>() {
            @Override
            public void onStarted(SimpleTarget target) {
                Feature feature = (Feature) target.getView().getTag();
                Log.e("on started", feature.name() + " asd");
            }
            @Override
            public void onEnded(SimpleTarget target) {
                Feature feature = (Feature) target.getView().getTag();
                Log.e("on ended", feature.name() + " asd");
            }
        })
        .build();
}
```

Show spotlight : 
```
public static void showSpotLights(final Activity activity, final SimpleTarget... targets) {
    Spotlight.with(activity)
            .setOverlayColor(ContextCompat.getColor(activity, R.color.background)) // background overlay color
            .setDuration(300L)
            .setAnimation(new DecelerateInterpolator(2f))
            .setTargets(targets)
            .setClosedOnTouchedOutside(true)
            .start();
}
```

Error message :

> 04-23 14:55:52.897: E/AndroidRuntime(4360): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference

**Comment by TakuSemba** [comment]
Hi, `SimpleTarget.Builder#setPoint(view View)` is used to just get the x, and y for spotlighting the target.


As you can see the code, `target.getView()` does not return the view you set the `setPoint`, it returns the overlay view cropped in circle. 

I think you should get the tag from the helpdeskButton itself.
Does it make sense?

**Comment by dhinx** [comment]
how to pas parameter to listener ?

so, if i have data to be proceed in started / ended listener

--
Ludvianto Ovandi
Handphone : 085 775 380 003

Facebook : https://www.facebook.com/ludvianto.ovandi
Twitter : https://twitter.com/dhinxdhonx

**Comment by TakuSemba** [comment]
you can pass listener to `generateTarget ()`

```java
public static SimpleTarget generateTarget(Activity activity, View point, String title, String description, OnTargetStateChangedListener<SimpleTarget> listener) {

}
```
