### ISSUE TITLE
assign target to view..

### ISSUE THREAD

**Issue by fadlifebriansyah** [TakuSemba/Spotlight#27]
Hi,

im trying to implement the library, but i cant put target as a view to method setPoint(textview1);

the round is not fit to the view..

any advice would help much.

thanks

**Comment by fadlifebriansyah** [comment]
SimpleTarget simpleTarget = new SimpleTarget.Builder(this)
                //location 1 = kiri kanan, location 2 = atas bawah
                .setPoint(findViewById(R.id.view1)) // position of the Target. setPoint(Point point), setPoint(View view) will work too.
                .setRadius(200f) // radius of the Target
                .setTitle(getResources().getString(R.string.preview_step1_title))
                .setDescription(getResources().getString(R.string.preview_step1_text))
                .setOnSpotlightStartedListener(new OnTargetStateChangedListener<SimpleTarget>() {
                    @Override
                    public void onStarted(SimpleTarget target) {
                        // do something
                    }

                    @Override
                    public void onEnded(SimpleTarget target) {
                        // do something
                    }
                })
                .build();

        Spotlight.with(PreviewActivity.this)
                .setOverlayColor(ContextCompat.getColor(PreviewActivity.this, R.color.background))
                .setDuration(1000L)
                .setAnimation(new DecelerateInterpolator(2f))
                .setTargets(simpleTarget)
                .setClosedOnTouchedOutside(true)
                .setOnSpotlightStartedListener(new OnSpotlightStartedListener() {
                    @Override
                    public void onStarted() {

                    }
                })
                .setOnSpotlightEndedListener(new OnSpotlightEndedListener() {
                    @Override
                    public void onEnded() {
                        ll1.setVisibility(View.VISIBLE);
                        btnClose1.setVisibility(View.VISIBLE);
                        btnNext1.setVisibility(View.VISIBLE);
                    }
                })
                .start();

**Comment by TakuSemba** [comment]
Can you give me a screenshot of how the spotlight isnt fit.

**Comment by AndresMorelos** [comment]
I had the same issue, the spotligth isn't fit

Code: 
```kotlin
Spotlight.with(this)
                .setOverlayColor(ContextCompat.getColor(this,R.color.background))
                .setDuration(1000L)
                .setAnimation(DecelerateInterpolator(2f))
                .setTargets(
                        SimpleTarget.Builder(this)
                                .setPoint(100f,Intentos.y)
                                .setRadius(100f)
                                .setTitle("Intentos")
                                .setDescription("Este es el contador de los intentos que has realizado,recuerada el maximo es 20!!.")
                                .build()
                ,
                        SimpleTarget.Builder(this)
                                .setPoint(Chronometer.x, Chronometer.y)
                                .setRadius(100f)
                                .setTitle("Cronometro")
                                .setDescription("Tiempo que ha pasado mientras intentas adivinar la palabra.")
                                .build()
                ,
                        SimpleTarget.Builder(this)
                                .setPoint(horizontalScrollView.x , horizontalScrollView.y)
                                .setTitle("Letras")
                                .setDescription("Cada botón representa una letra o caracter, puedes buscar el que necesites pasando el dedo de izquierda a derecha o viceversa")
                                .build()
                )
                .setClosedOnTouchedOutside(true)
                .setOnSpotlightStartedListener {

                }
                .setOnSpotlightEndedListener {

                }
                .start()
```

Image:
![whatsapp image 2018-04-27 at 9 22 51 am](https://user-images.githubusercontent.com/6563162/39367637-034e33d6-49fd-11e8-9acd-7d6f8756d420.jpeg)

**Comment by TakuSemba** [comment]
Can you try after view is located as I described in Read.me?

```
view.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
    @Override public void onGlobalLayout() {
        view.getViewTreeObserver().removeOnGlobalLayoutListener(this);
        // show spotlight here
    }
});
```

**Comment by AndresMorelos** [comment]
```kotlin
Instrucciones.getViewTreeObserver().addOnGlobalLayoutListener{
            object : ViewTreeObserver.OnGlobalLayoutListener {
                override fun onGlobalLayout() {
                    Instrucciones.viewTreeObserver.removeOnGlobalLayoutListener(this)
                    Spotlight.with(this@instructions)
                            .setOverlayColor(ContextCompat.getColor(this@instructions, R.color.background))
                            .setDuration(1000L)
                            .setAnimation(DecelerateInterpolator(2f))
                            .setTargets(
                                    SimpleTarget.Builder(this@instructions)
                                            .setPoint(Intentos)
                                            .setRadius(100f)
                                            .setTitle("Intentos")
                                            .setDescription("Este es el contador de los intentos que has realizado,recuerada el maximo es 20!!.")
                                            .build()
                                    ,
                                    SimpleTarget.Builder(this@instructions)
                                            .setPoint(Chronometer)
                                            .setRadius(100f)
                                            .setTitle("Cronometro")
                                            .setDescription("Tiempo que ha pasado mientras intentas adivinar la palabra.")
                                            .build()
                                    ,
                                    SimpleTarget.Builder(this@instructions)
                                            .setPoint(horizontalScrollView)
                                            .setTitle("Letras")
                                            .setDescription("Cada botón representa una letra o caracter, puedes buscar el que necesites pasando el dedo de izquierda a derecha o viceversa")
                                            .build()
                            )
                            .setClosedOnTouchedOutside(true)
                            .setOnSpotlightStartedListener {

                            }
                            .setOnSpotlightEndedListener {

                            }
                            .start()
                }

            }

        }
```

with this code the spotlight doesn't start/show

**Comment by TakuSemba** [comment]
the code above, is the callback even called?
you mean the callback of the onGlobalLayout is called but spotlight doesnt start?

**Comment by TakuSemba** [comment]
sorry, closing this issue as not seeing your response.
