### ISSUE TITLE
Logo/icon Proposal for Spotlight

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [TakuSemba/Spotlight#28]
Hello,
This my logo/Icon design for your project. It's free for your project.

I design this logo using adobe illustrator cc 2017. I hope you like this logo.

![spotlight-01-01](https://user-images.githubusercontent.com/35112507/39064483-7d934710-44f0-11e8-8280-69a6faa4c0f3.jpg)

which type you need plz tell me.
If you need anything change please contact me

Md Nazmul Hasan
Email : nazmul.hasan27771@gmail.com

Thank You.

**Comment by TakuSemba** [comment]
thank you for your proposal.
I appreciate it, but currently im not thinking of changing the icon or logo.

I'll get a hold of you, when i need it.
