### ISSUE TITLE
Add "Skip tutorial" button

### ISSUE THREAD

**Issue by AroundPixels** [TakuSemba/Spotlight#30]
Hi. First of all, thank you for so great library. I have a question, is there any way to add a button (not a target) visible all time over the overlay to add any special action? In my case would be a "Skip intro/tutorial" to close spotlight before all targets have been shown.

Thanks

**Comment by TakuSemba** [comment]
thank you for the suggestion, I added that feature at the version of 1.5.0!
try that out!

```java
Spotlight spotlight = Spotlight.with(this)...start();

spotlight.closeSpotlight();
```

**Comment by AroundPixels** [comment]
Thank you so much @TakuSemba 👍
