### ISSUE TITLE
Add "show once only" feature

### ISSUE THREAD

**Issue by taar1** [TakuSemba/Spotlight#31]
In its current state we have to handle the limiting of the displaying ourselves. It would be great if there was a feature in the api where we can define that the spotlight is displayed only once.

**Comment by rcraggs** [comment]
I thing this use case doesn't belong in the library itself. There are other ways of achieving this - e.g. https://github.com/jonfinerty/Once

**Comment by TakuSemba** [comment]
for now, you have to save the flag on your side and control if you show the spotlight or not.
thank you for the request, but unfortunately there is no plan to implement that. 
I will let you know when I do this.
