### ISSUE TITLE
setTargets with ArrayList of Targets as parameter

### ISSUE THREAD

**Issue by mourjan** [TakuSemba/Spotlight#33]
Good day and thank you for providing the long waited custom shape feature,

could you kindly provide another setTargets method that takes an ArrayList of CustomTargets or SimpleTargets?
It is needed when number of targets is dynamic.

or do you prefer that I fork the project and return with a pull request?

**Comment by TakuSemba** [comment]
Thanks, great idea.

I will try to implement it when i have time,  or your pull request is also welcome!

**Comment by mourjan** [comment]
I did a pull request with changes, and thanks again

**Comment by TakuSemba** [comment]
now you can try it as of the version of 1.5.1. again, thank you for the PR.

**Comment by mourjan** [comment]
I did and it saved me from ~30 lines of if-else statements.. cheers
