### ISSUE TITLE
Make SpotlightView/Targetclickable

### ISSUE THREAD

**Issue by nikhilpanju** [TakuSemba/Spotlight#35]
Can you make spotlightview or the target clickable? I know we can make a custom view and set clickable there but it would be great to make the target itself clickable to make the user tap on the target to move forward

**Comment by TakuSemba** [comment]
The target is a clipped area.
so if you want to click the clipped area, i think you could set a listener on your view targeting.

**Comment by RobertoAlvarezCeballos** [comment]
I´m trying the same thing right now. The whole SpotView has the click event, there is no easy way to detect onclick only on the target area. 

Any ideas are welcome

**Comment by TakuSemba** [comment]
sorry, i was wrong.

To work it around, you have to use an customTarget and set an listener on the view on the CustomTarget.

I will try to improve this, but I can tell when so far, sorry.

**Comment by chintan369** [comment]
Is this now clickable a target or shape in the current version?
