### ISSUE TITLE
Coachmark with Dialog

### ISSUE THREAD

**Issue by mnnit-LaltuKumar** [TakuSemba/Spotlight#36]
Its an awesome library but I have a query how do I show the coachmark over the dialog. Its always coming behind the dialog. I am using the DialogFragment with animation in android.

**Comment by sabih1998** [comment]
I have the same problem.
I use BottomSheetDialog and it come behind the bottomSheet.

**Comment by tudormarze** [comment]
@TakuSemba I have opened a pull request for this issue. Found that `Dialog` creates its own `Window`, which is different from `Activity.getWindow()`

**Comment by sumit269** [comment]
Does this issue still exist?

**Comment by mnnit-LaltuKumar** [comment]
I have solved the issue.
