### ISSUE TITLE
How to draw a rectangle not a circle?

### ISSUE THREAD

**Issue by MohamedAssemAli** [TakuSemba/Spotlight#43]
I tried to change the chosen shape to a rectangle but it doesn't work

**Comment by MohamedAssemAli** [comment]
I have solved it myself

**Comment by MohamedAssemAli** [comment]
Add this class 

`package com.takusemba.spotlight.shape;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.PointF;

public class Rectangle implements Shape {

    private float left, top, right, bottom;

    public Rectangle(float left, float top, float right, float bottom) {
        this.left = left;
        this.top = top;
        this.right = right;
        this.bottom = bottom;
    }


    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
          /*
                    public Rect (int left, int top, int right, int bottom)
                        Create a new rectangle with the specified coordinates. Note: no range
                        checking is performed, so the caller must ensure that left <= right and
                        top <= bottom.

                    Parameters
                        left : The X coordinate of the left side of the rectangle
                        top : The Y coordinate of the top of the rectangle
                        right : The X coordinate of the right side of the rectangle
                        bottom : The Y coordinate of the bottom of the rectangle

                */
        canvas.drawRect(left, top, right, bottom, paint);

    }

    @Override
    public int getHeight() {
        return (int) (bottom - top);
    }

    @Override
    public int getWidth() {
        return (int) (right - left);
    }
}
`

**Comment by MohamedAssemAli** [comment]
Add this class: 


`

package com.takusemba.spotlight.shape;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.PointF;

public class Rectangle implements Shape {

    private float left, top, right, bottom;

    public Rectangle(float left, float top, float right, float bottom) {
        this.left = left;
        this.top = top;
        this.right = right;
        this.bottom = bottom;
    }


    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
          /*
                    public Rect (int left, int top, int right, int bottom)
                        Create a new rectangle with the specified coordinates. Note: no range
                        checking is performed, so the caller must ensure that left <= right and
                        top <= bottom.

                    Parameters
                        left : The X coordinate of the left side of the rectangle
                        top : The Y coordinate of the top of the rectangle
                        right : The X coordinate of the right side of the rectangle
                        bottom : The Y coordinate of the bottom of the rectangle

                */
        canvas.drawRect(left, top, right, bottom, paint);

    }

    @Override
    public int getHeight() {
        return (int) (bottom - top);
    }

    @Override
    public int getWidth() {
        return (int) (right - left);
    }
}




`

**Comment by MohamedAssemAli** [comment]
I have solved by myself, i will comment solutions after testing many cases

**Comment by hiddeneyes02** [comment]
Can you tell how did you achieve this please? I tried this, but it is not working:

```
public class RectShape implements Shape {

   private View view;

   public RectShape(View v) {
      view = v;
   }

   @Override
   public void draw(Canvas canvas, PointF point, float value, Paint paint) {
      Paint myPaint = new Paint();
      myPaint.setColor(view.getContext().getResources().getColor(android.R.color.transparent));
      myPaint.setStrokeWidth(0);
      Rect rect = new Rect();
      view.getGlobalVisibleRect(rect);
      canvas.drawRect(rect, myPaint);
   }

   @Override
   public int getHeight() {
      return view.getHeight();
   }

   @Override
   public int getWidth() {
      return view.getWidth();
   }
}
```

**Comment by Almaral-Engineering** [comment]
Same here, it does not wrok

**Comment by MohamedAssemAli** [comment]
`
public class Rectangle implements Shape {

    private float left, top, right, bottom;

    public Rectangle(float left, float top, float right, float bottom) {
        this.left = left;
        this.top = top;
        this.right = right;
        this.bottom = bottom;
    }


    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
          /*
                        public Rect (int left, int top, int right, int bottom)
                        Create a new rectangle with the specified coordinates. Note: no range
                        checking is performed, so the caller must ensure that left <= right and
                        top <= bottom.

                        Parameters
                        left : The X coordinate of the left side of the rectangle
                        top : The Y coordinate of the top of the rectangle
                        right : The X coordinate of the right side of the rectangle
                        bottom : The Y coordinate of the bottom of the rectangle

                */
        canvas.drawRect(value * left, top, value * right, bottom, paint);
    }

    @Override
    public int getHeight() {
        return (int) (bottom - top);
    }

    @Override
    public int getWidth() {
        return (int) (right - left);
    }
}
`

**Comment by MohamedAssemAli** [comment]
Here you can check it 

`

public class Rectangle implements Shape {

    private float left, top, right, bottom;

    public Rectangle(float left, float top, float right, float bottom) {
        this.left = left;
        this.top = top;
        this.right = right;
        this.bottom = bottom;
    }


    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
          /*
                        public Rect (int left, int top, int right, int bottom)
                        Create a new rectangle with the specified coordinates. Note: no range
                        checking is performed, so the caller must ensure that left <= right and
                        top <= bottom.

                        Parameters
                        left : The X coordinate of the left side of the rectangle
                        top : The Y coordinate of the top of the rectangle
                        right : The X coordinate of the right side of the rectangle
                        bottom : The Y coordinate of the bottom of the rectangle

                */
        canvas.drawRect(value * left, top, value * right, bottom, paint);
    }

    @Override
    public int getHeight() {
        return (int) (bottom - top);
    }

    @Override
    public int getWidth() {
        return (int) (right - left);
    }
}


`

**Comment by JonathandelaSen** [comment]
I know this is closed but I have another solution I would like to share.

`


    private View view;
    private int margin;

    public CopyViewFormShape(View view, int margin) {
        this.view = view;
        this.margin = margin;
    }

    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        canvas.drawRect(getRectWithMargins(point, value), paint);
    }

    @Override
    public int getHeight() {
        return view.getHeight();
    }

    @Override
    public int getWidth() {
        return view.getWidth();
    }

    private Rect getRectWithMargins(PointF point, float value) {
        return new Rect(
                (int) (point.x - ( (view.getWidth()/2) * value)) - margin,
                (int) (point.y - ( (view.getHeight()/2) * value)) - margin,
                (int) (point.x + ( (view.getWidth()/2) * value)) + margin,
                (int) (point.y + ( (view.getHeight()/2) * value)) + margin);
    }


`

**Comment by nikulcears** [comment]
> I added a Rounded Rectangle as of the version of 1.8.0.
> Please try that!
can you please explain which function we have to use? in case of rectangle in 2.0.1
