### ISSUE TITLE
title and text on spot

### ISSUE THREAD

**Issue by mojtabas74** [TakuSemba/Spotlight#45]
hi i make a round rectangle for my app's help, everything fine but texts show on spot.
you  can see this problem on pictures .
 
![screenshot_20180726-020304](https://user-images.githubusercontent.com/16499429/43229041-9d6687a4-9078-11e8-84eb-498057611891.jpg)
![screenshot_20180726-020236](https://user-images.githubusercontent.com/16499429/43229059-b2314bb0-9078-11e8-891e-45f192167aef.jpg)

**Comment by TakuSemba** [comment]
thank you for reporting. I will look into it.

**Comment by TakuSemba** [comment]
can i see the class implemented shape class?

**Comment by mojtabas74** [comment]
yes here:


import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.PointF;

import com.takusemba.spotlight.shape.Shape;



public class RoundRectangle1 implements Shape {

    private float width;
    private float height;

    public RoundRectangle1(float width, float height) {
        this.width = width;
        this.height = height;
    }

    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        canvas.drawRect(point.x, point.y,  point.x+(width),point.y+(height), paint);

    }

    @Override
    public int getHeight() {
        return 0;
    }

    @Override
    public int getWidth() {
        return 0;
    }



}

**Comment by mojtabas74** [comment]
and i call it like this:

` imgHelpShowVideo=(ImageView) findViewById(R.id.imgHelpShowVideo) ;
        imgHelpShowVideo.setOnClickListener(new View.OnClickListener() {
            @SuppressLint("ResourceType")
            @Override
            public void onClick(View view) {
                if(!G.IsHelpOn) {
                    final SimpleTarget[] firstTarget = new SimpleTarget[8];
                    final View one[] = new View[8];
                    String PostTitle[] = new String[8];
                    String PostDescrib[] = new String[8];
                    one[0] = findViewById(R.id.LayoutVideoShowHolder);
                    one[1] = findViewById(R.id.SeekVideoShowPlayer);
                    one[2] = findViewById(R.id.TxtVideoShowMin);
                    one[3] = findViewById(R.id.TxtVideoShowMax);
                    one[4] = findViewById(R.id.btnVideoShowNext);
                    one[5] = findViewById(R.id.btnVideoShowPervuis);
                    one[6] = findViewById(R.id.TxtVideoShowNumberOfVideo);
                    one[7] = findViewById(R.id.btnSaveVideoShow);
                    PostTitle[0] = "قسمتِ در حال نمایش";
                    PostTitle[1] = "نوار زمان";
                    PostTitle[2] = "زمان گذشته";
                    PostTitle[3] = "زمان کل";
                    PostTitle[4] = "قسمت بعدی";
                    PostTitle[5] = "قسمت قبلی";
                    PostTitle[6] = "تعداد قسمت";
                    PostTitle[7] = "ذخیره";

                    PostDescrib[0] = "قسمت های برش داده شده در این قسمت نمایش داده می شوند و همچنین با لمس آن می توانید فیلم را متوقف یا پخش کنید.";
                    PostDescrib[1] = "با استفاده از نوار موجود می توانید فیلم را به جلو یا عقب ببرید.";
                    PostDescrib[2] = "زمان گذشته از شروع فیلم در این قسمت نشان داده می شود.";
                    PostDescrib[3] = "کل زمان فیلم در این قسمت نشان داده می شود.";
                    PostDescrib[4] = "با استفاده از این دکمه می توانید به قسمت بعدی بروید.";
                    PostDescrib[5] = "با استفاده از این دکمه می توانید به قسمت قبلی بروید.";
                    PostDescrib[6] = "قسمت کنونی و تعداد کل قسمت ها در این جا نشان داده می شود.";
                    PostDescrib[7] = "با این دکمه می توانید همه ی فیلم ها را ذخیره کنید.(در حالت رایگان تنها 2 قسمت ذخیره می شود.)";


                    for (int i = 0; i < 8; i++) {


                        final int[] oneLocation = new int[2];
                        one[i].getLocationInWindow(oneLocation);
                        final float oneX = oneLocation[0] ;
                        final float oneY = oneLocation[1] ;
                        firstTarget[i] = new SimpleTarget.Builder(G.currentActivity).setPoint(oneX, oneY)
                                .setShape(new RoundRectangle1(one[i].getWidth(),one[i].getHeight()) )
                                .setTitle(PostTitle[i])
                                .setDescription(PostDescrib[i])
                                .build();
                    }

                    Spotlight.with(G.currentActivity)
                            .setOverlayColor( R.color.background)
                            .setDuration(500L)
                            .setAnimation(new DecelerateInterpolator(2f))
                            .setTargets(firstTarget[0], firstTarget[1], firstTarget[2], firstTarget[3], firstTarget[4], firstTarget[5], firstTarget[6], firstTarget[7])
                            .setClosedOnTouchedOutside(true)
                            .setOnSpotlightStateListener(new OnSpotlightStateChangedListener() {
                                @Override
                                public void onStarted() {
                                    G.IsHelpOn=true;
                                }

                                @Override
                                public void onEnded() {
                                    SharedPreferences.Editor editor = Help.preferences.edit();
                                    editor.putBoolean("HelpShowVideo", true);
                                    editor.apply();
                                    G.IsHelpOn=false;
                                }
                            })
                            .start();
                }
            }
        });`

**Comment by TakuSemba** [comment]
you have to return the height and the width to calculate the text's position

```java

public class RoundRectangle1 implements Shape {

    private float width;
    private float height;

    public RoundRectangle1(float width, float height) {
        this.width = width;
        this.height = height;
    }

    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        canvas.drawRect(point.x, point.y,  point.x+(width),point.y+(height), paint);

    }

    @Override
    public int getHeight() {
        return height;
    }

    @Override
    public int getWidth() {
        return width;
    }
```

**Comment by mojtabas74** [comment]
yes it work for some target but not all 

```
public class RoundRectangle1 implements Shape {

    private float width;
    private float height;

    public RoundRectangle1(float width, float height) {
        this.width = width;
        this.height = height;
    }

    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        canvas.drawRect(point.x, point.y,  point.x+(width),point.y+(height), paint);

    }

    @Override
    public int getHeight() {
        return (int)height;
    }

    @Override
    public int getWidth() {
        return (int)width;
    }



}
```

![screenshot_20180726-152013](https://user-images.githubusercontent.com/16499429/43258308-9bcd7e10-90e7-11e8-85a3-abe158c4ee69.jpg)
![screenshot_20180726-152033](https://user-images.githubusercontent.com/16499429/43258310-9c47d4f8-90e7-11e8-9e6c-51a591a96ffd.jpg)
![screenshot_20180726-152022](https://user-images.githubusercontent.com/16499429/43258311-9cbd1146-90e7-11e8-900d-cffa830e8b95.jpg)

**Comment by TakuSemba** [comment]
inside draw function,  the height and the width you are drawing is bigger than what you specified in getWidth, and getHeight.

**getWidth(), and getHeight() should be the same size of the shape you are drawing in draw()**

```java
    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        canvas.drawRect(point.x, point.y,  point.x+(width),point.y+(height), paint);

    }
```

**Comment by mojtabas74** [comment]
i have no problem with size of shape in the picture you can see the shape find very well i try 
```
    @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        canvas.drawRect(point.x, point.y,  value * width, value * height, paint);

    }
```
but shapes not find at all .
the problem is text show on target

**Comment by TakuSemba** [comment]
this is draw interface, i dont understand why left, top, right, bottom are point.x, point.y, point.x + width, point.y + height. 

you have to use float value, because it keep changing from 0.0 to 1.0.
I think you are not drawing in a right way. 

you can use custom target, if you want to set your view where you want to put.

**Comment by TakuSemba** [comment]
I think this pr would be useful for you to create rectangle custom shape.

https://github.com/TakuSemba/Spotlight/pull/46

**Comment by mojtabas74** [comment]
look i get my target position and Width Height and give position to setPoints and get Width and Height to RoundRectange my code is:
```
  final SimpleTarget[] firstTarget = new SimpleTarget[5];
        View one[] = new View[5];
        one[0] = View.findViewById(R.id.LPost1);
        one[1] = View.findViewById(R.id.LPost2);
        one[2] = View.findViewById(R.id.LPost3);
        one[3] = View.findViewById(R.id.LPost4);
        one[4] = View.findViewById(R.id.LPost5);
        for(int i=0;i<5;i++) {
            int[] oneLocation = new int[2];
            one[i].getLocationInWindow(oneLocation);
            Log.i("AAAAAAAAAAAAA", "" + oneLocation[0]+ one[i].getWidth());
            Log.i("AAAAAAAAAAAAA", "" + oneLocation[1]+ one[i].getHeight());
            Log.i("AAAAAAAAAAAAA", "" + one[i].getWidth());
            Log.i("AAAAAAAAAAAAA", "" + one[i].getHeight());
            float oneX = oneLocation[0];
            float oneY = oneLocation[1];
            // make an target
            firstTarget[i] = new SimpleTarget.Builder(G.currentActivity).setPoint(oneX, oneY)
                    .setShape(new  RoundRectangle1(one[i].getWidth(),one[i].getHeight()) )
                    .setTitle(PostTitle[i])
                    .setDescription(PostDescrib[i])

                    .build();
        }
```
after that in RoundRectangle class i start draw from starting point(setPoint(oneX, oneY)) to starting point + size of shape (point.x+(width),point.y+(height)) my code is :
```
public class RoundRectangle1 implements Shape {

    private float width;
    private float height;

    public RoundRectangle1(float width, float height) {
        this.width = width;
        this.height = height;
    }

      @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        Log.i("a","point.x "+point.x+"point.y "+point.y);
        Log.i("a","width "+width+"height "+height);
        canvas.drawRect(point.x, point.y,  point.x+(width),point.y+(height), paint);

    }

    @Override
    public int getHeight() {
        return (int)height;
    }

    @Override
    public int getWidth() {
        return (int)width;
    }

}
```
so everything work fine and my target find very-well Like this:
![screenshot_20180726-152013](https://user-images.githubusercontent.com/16499429/43272255-c5168f38-910e-11e8-8606-1bc90a446906.jpg)

but you can see text show on target so finding target  work fine but text position not right .

and i use log to show positions of targets and size of them and Output is:

07-26 20:04:27.031 6693-6693/com.ariaroid.postmaker I/a: point.x 222.0point.y 640.0
    width 798.0height 260.0

**Comment by TakuSemba** [comment]
the problem is here. 

```java
      @Override
    public void draw(Canvas canvas, PointF point, float value, Paint paint) {
        Log.i("a","point.x "+point.x+"point.y "+point.y);
        Log.i("a","width "+width+"height "+height);
        canvas.drawRect(point.x, point.y,  point.x+(width),point.y+(height), paint);
    }

```

point.x, and point.y should be the center of the shape.
you set them to be left and top. thats why text position is not right.

why are you setting point.x and point.y at top and left.

**Comment by TakuSemba** [comment]
if you want to do that. you can not use simpleTarget. use Custom Target instead.
