### ISSUE TITLE
setOverlayColor error

### ISSUE THREAD

**Issue by nqphuc94** [TakuSemba/Spotlight#47]
I get error message "Android Release error: Expected a color resource id (R.color.) but received an RGB integer" when try call 
<b>setOverlayColor(ContextCompat.getColor(MainActivity.this, R.color.background))</b>

Possible cause by annotation @ColorRes in your define method setOverlayColor

**Comment by TakuSemba** [comment]
can you pass color resource id? instead of RGB integer?

**Comment by nqphuc94** [comment]
**setOverlayColor(R.color.background)** is good, instead of setOverlayColor(ContextCompat.getColor(MainActivity.this, R.color.background))

you should update README.md file

**Comment by TakuSemba** [comment]
I fixed it, thank you for telling me!
