### ISSUE TITLE
how to set spot in menuItem?

### ISSUE THREAD

**Issue by Kelvao** [TakuSemba/Spotlight#48]
menu item doesn't have "getLocationWindow"

**Comment by TakuSemba** [comment]
sorry? I dont understand your question or issue.

**Comment by Kelvao** [comment]
how can i set spotlight in menu item from my toobar?

**Comment by TakuSemba** [comment]
I see.

To set a spotlight, you need the location of the view. 
if you cant get it, setting a spot is not achievable.

**Comment by mariantoni** [comment]
I resolved using 
`val viewTreeObserver = window.decorView.viewTreeObserver
        viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
            override fun onGlobalLayout() {
                
            }
        })  `
Inside only use de id of item menu
`val view1 = findViewById<View>(R.id.action)`
Where 
`<menu
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">
    <item
        android:id="@+id/action"
        android:icon="@drawable/ic_web"
        android:title="@string/about_toolbar"
        android:visible="true"
        app:showAsAction="always" />`
