### ISSUE TITLE
can't work when Build.VERSION.SDK_INT less than LOLLIPOP

### ISSUE THREAD

**Issue by LongAgoLong** [TakuSemba/Spotlight#49]
can't work when Build.VERSION.SDK_INT less than LOLLIPOP

**Comment by TakuSemba** [comment]
Hi, I tested on a Kitkat device and worked as expected.
Could you describe how it didn't work so that I can look into it?

I'm closing this issue for now.
Please reopen this with more detailed information.
I'm happy to help you.
