### ISSUE TITLE
Spotlight isn't centered properly for some targets

### ISSUE THREAD

**Issue by UsernameInvalidException** [TakuSemba/Spotlight#5]
For some targets, the spotlight is centered correctly, but for others, it is centered on the corner of the target. Example:

![screenshot_20170710-171444-2](https://user-images.githubusercontent.com/28464769/28040802-fe2dd3c2-6594-11e7-82dc-b6897cb810f7.png)

**Comment by TakuSemba** [comment]
thanks for telling me, i will look into it.

**Comment by TakuSemba** [comment]
can you show me the code? @UsernameInvalidException

**Comment by UsernameInvalidException** [comment]
@TakuSemba The code that created the above example?

**Comment by TakuSemba** [comment]
yes. @UsernameInvalidException

**Comment by UsernameInvalidException** [comment]
@TakuSemba Well, have a look in [this file](https://github.com/HueToYou/ChatExchange/blob/ee872a6b9107368f58f5cdf2672c24573edd3527/app/src/main/java/com/huetoyou/chatexchange/ui/misc/TutorialStuff.java). The `swipeToDel` spotlight [(line 291)](https://github.com/HueToYou/ChatExchange/blob/ee872a6b9107368f58f5cdf2672c24573edd3527/app/src/main/java/com/huetoyou/chatexchange/ui/misc/TutorialStuff.java#L291) and the `recyclerSpotlight` [(line 331)](https://github.com/HueToYou/ChatExchange/blob/ee872a6b9107368f58f5cdf2672c24573edd3527/app/src/main/java/com/huetoyou/chatexchange/ui/misc/TutorialStuff.java#L331) are the problematic ones.

**Comment by zhangruize** [comment]
should be wrong with `setPoint` method.

**Comment by TakuSemba** [comment]
the source code is pretty simple as you see below

```java
    public T setPoint(@NonNull View view) {
        int[] location = new int[2];
        view.getLocationInWindow(location);
        int x = location[0] + view.getWidth() / 2;
        int y = location[1] + view.getHeight() / 2;
        return setPoint(x, y);
    }
```

location[0] is view's left edge, location[1] is view's top edge. 
can you check and tell me, each location[0], location[1], view.getWidth(), and view.getHeight() are what you expected.

@UsernameInvalidException
