### ISSUE TITLE
.setTargets(targets) does not work

### ISSUE THREAD

**Issue by agrajdek** [TakuSemba/Spotlight#50]
I was trying to set targets added to ArrayList but I get this error
![image](https://user-images.githubusercontent.com/3735307/45812688-cc345000-bcd0-11e8-96ef-4886394dc4d9.png)

**Comment by TakuSemba** [comment]
can you provide me a branch that i can test it?

**Comment by TakuSemba** [comment]
I'm closing this due to the lack of information.
