### ISSUE TITLE
Add animation in custom shape

### ISSUE THREAD

**Issue by JulioManzano** [TakuSemba/Spotlight#52]
how can I add an animation for a custom shape

**Comment by m-Samhoury** [comment]
To animate custom shape just do this:
Here I created a rectangular shape for a button, multiplying with the value parameter does the job of animating the custom shape.

Find below the code snippet(Kotlin):
 ```
 override fun draw(canvas: Canvas?, point: PointF?, value: Float, paint: Paint?) {
                canvas?.drawRect((point?.x ?: 0f),
                        (point?.y ?: 0f),
                        ((point?.x ?: 0f) + width) * value,
                        ((point?.y ?: 0f) + height) * value, paint)
            }
```

**Comment by TakuSemba** [comment]
Yep. You can create a custom shape to tweak the animation. 
Thank you @m-Samhoury .
