### ISSUE TITLE
how set Font for title and Description ?

### ISSUE THREAD

**Issue by abolfazlkalamati** [TakuSemba/Spotlight#58]

**Comment by TakuSemba** [comment]
you can not set Font on SimpleTarget. CustomTarget works for you i think.

**Comment by abolfazlkalamati** [comment]
thanks - i use CustomTarget and set Font for Spotlight .

        LayoutInflater inflater = LayoutInflater.from(context);
        View first = inflater.inflate(R.layout.walk_throughs_view, null);
        TextView titleOne = first.findViewById(R.id.title_text);
        titleOne.setText("استعلام دستی");
        titleOne.setTypeface(MyFont);
       

        CustomTarget firstTarget =
                new CustomTarget.Builder(ActivityArchive.this).setPoint(200,400)
                        .setRadius(85f)
                        .setView(first)
                        .build();

     Spotlight.with(ActivityArchive.this)
                .setDuration(1000L)
                .setAnimation(new DecelerateInterpolator(2f))
                .setTargets(firstTarget)
                .setOnSpotlightStartedListener(new OnSpotlightStartedListener() {
                    @Override
                    public void onStarted() {

                    }
                })
                .setOnSpotlightEndedListener(new OnSpotlightEndedListener() {
                    @Override
                    public void onEnded() {
                    }
                })
                .start();

**Comment by abolfazlkalamati** [comment]
` LayoutInflater inflater = LayoutInflater.from(context);
        View first = inflater.inflate(R.layout.walk_throughs_view, null);
        TextView titleOne = first.findViewById(R.id.title_text);
        TextView descriptionOne = first.findViewById(R.id.description_text);
        titleOne.setText("استعلام دستی");
        descriptionOne.setText(" انتخاب تصویر چک از گالری");
        titleOne.setTypeface(bold);
        descriptionOne.setTypeface(light);

        CustomTarget firstTarget =
                new CustomTarget.Builder(ActivityArchive.this).setPoint(importImage)
                        .setRadius(85f)
                        .setView(first)
                        .build();`

**Comment by abolfazlkalamati** [comment]
thanks , i use CustomTarget and work it .

        LayoutInflater inflater = LayoutInflater.from(context);
        View first = inflater.inflate(R.layout.walk_throughs_view, null);
        TextView titleOne = first.findViewById(R.id.title_text);
        titleOne.setText("استعلام دستی");
        titleOne.setTypeface(bold);

        CustomTarget firstTarget =
                new CustomTarget.Builder(ActivityArchive.this).setPoint(333,500)
                        .setRadius(85f)
                        .setView(first)
                        .build();

 Spotlight.with(ActivityArchive.this)
                .setDuration(1000L)
                .setAnimation(new DecelerateInterpolator(2f))
                .setTargets(firstTarget)
                .setOnSpotlightStartedListener(new OnSpotlightStartedListener() {
                    @Override
                    public void onStarted() {

                    }
                })
                .setOnSpotlightEndedListener(new OnSpotlightEndedListener() {
                    @Override
                    public void onEnded() {
                    }
                })
                .start();

**Comment by TakuSemba** [comment]
I'm closing this because `SimpleTarget` is removed at the version of 2.0.0
