### ISSUE TITLE
Spotlight position between phones

### ISSUE THREAD

**Issue by krisdb** [TakuSemba/Spotlight#61]
The spotlight position is different between two phone.  A Pixel 2 XL emulator looks like this:

https://i.imgur.com/G7Lcrmq.png

but on a Pixel 3 XL phone (no emulator) it's here:

https://i.imgur.com/7qddSSE.png

I'm thinking the notch might be effecting the positioning.

I'm also using 1.5.0 because 1.8.0 is throwing some manifest merge compiling error.

**Comment by ghataa** [comment]
Same here with positioning!

**Comment by TakuSemba** [comment]
> I'm also using 1.5.0 because 1.8.0 is throwing some manifest merge compiling error.

take a look at this issue https://github.com/TakuSemba/Spotlight/issues/63

**Comment by TakuSemba** [comment]
I tested on Pixel 3 XL but could not reproduce it on the demo app.
Can you reproduce it on the demo app and share the branch so that I can look into it?

**Comment by TakuSemba** [comment]
I think this happens when you use both `setAnchor(view)` and `setContainer()` and the anchor does not take the container position into consideration.

I believe I fixed it on v2.0.2.
Please reopen this, if it still happens.

**Comment by lrnrzg** [comment]
the solustion can produce new bug when you setAnchor(x,y) and set Container whose coordinate is not (0,0) on screen, I fix it by create the [pr ](https://github.com/TakuSemba/Spotlight/pull/137)
