### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by saviart** [TakuSemba/Spotlight#63]
i had a issues. please help me.

"Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-24:19 to override."

**Comment by dilipkumar4813** [comment]
Go to your gradle.properties file and add the following lines

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by jobingn** [comment]
I am getting compilation error. Unresolved reference

**Comment by dilipkumar4813** [comment]
> I am getting compilation error. Unresolved reference

Need more information on the error. A possibility is that since the library is using Androidx you would have to tailor your code for Androidx

**Comment by TakuSemba** [comment]
Yes, I think https://github.com/TakuSemba/Spotlight/issues/63#issuecomment-466261294 would solve the issue.

**Comment by TakuSemba** [comment]
I'm closing this because it seems like the issue was solved.
