### ISSUE TITLE
<setPoint> in <SimpleTarget> mode

### ISSUE THREAD

**Issue by Mr-ARBN** [TakuSemba/Spotlight#66]
`SimpleTarget firstTarget = new SimpleTarget.Builder(this)
.setPoint(findViewById(R.id.one))
.setShape(new Circle(100f))
.setTitle("the title")
.setDescription("the description")
.setOverlayPoint(100f, 100f)
.setOnSpotlightStartedListener(new OnTargetStateChangedListener<SimpleTarget>()
`
setPoint doesn't work on SimpleTarget.
it goes to top left in application, in the corner.

**Comment by TakuSemba** [comment]
make sure you call `setPoint(findViewById(R.id.one))`  after views are inflated.

**Comment by TakuSemba** [comment]
I'm closing this because `SimpleTarget` is removed as of the version of 2.0.0
