### ISSUE TITLE
Show previous target

### ISSUE THREAD

**Issue by Elvereth** [TakuSemba/Spotlight#67]
Hello,

is there a method or some workaround to show the previous target?
For moving to the next one we have _spotlight.closeCurrentTarget()_, anything similar for going back would be useful. 

In this way for example in a tutorial you can have all kind of buttons, **skip**, **next** but also **back**.

**Comment by Fatimamostafa** [comment]
Can you please share what's the skip method?

**Comment by Elvereth** [comment]
> Can you please share what's the skip method?

You can use _spotlight.closeSpotlight()_ to skip it and close it altogether.

**Comment by Fatimamostafa** [comment]
@TakuSemba can you please look at the issue

**Comment by TakuSemba** [comment]
> is there a method or some workaround to show the previous target?

Unfortunate, There is no way to archive that for now.

**Comment by TakuSemba** [comment]
As of 2.0.0, you can go back to the previous target with Spotlight#previous().
Thank you.
