### ISSUE TITLE
Can to start spotlight whit Spotlight spotlight=Spotlight.with(this)...start

### ISSUE THREAD

**Issue by snip77** [TakuSemba/Spotlight#69]
hi
i want to skip splotlight after a time so i set spotlight object in variable :
`Spotlight spotlight=Spotlight.with(this)...start();`

but i have a erorr `incompatible type` that start return void and we need spotlight object !

**Comment by kellypitts91** [comment]
I know this is old but if anyone else comes across the issue as well.
I had the same issue, if you do the following it will work
`Spotlight spotlight = Spotlight.with(this);
...
spotlight.start()`
