### ISSUE TITLE
view

### ISSUE THREAD

**Issue by Dream-cxc** [TakuSemba/Spotlight#7]
If you want to achieve such as the effect of the map, used to indicate the progress, what is the good way?

**Comment by TakuSemba** [comment]
> the effect of the map

well, I dont understand what your saying. can you show me a image or gif???

**Comment by Dream-cxc** [comment]
I am sorry, my ability to express is not very good, I have encountered such a netizen, their boss needs him to achieve your gif style flow chart,

**Comment by TakuSemba** [comment]
what you can do is the animation on [read.me](https://github.com/TakuSemba/Spotlight/blob/master/README.md).
there is nothing more than that....

**Comment by Dream-cxc** [comment]
Is that the effect map the company's needs?

**Comment by TakuSemba** [comment]
well, no. I created it personally.
