### ISSUE TITLE
error: duplicate value for resource 'attr/fontStyle' with config ''.

### ISSUE THREAD

**Issue by nagarajks88** [TakuSemba/Spotlight#75]
Once I imported 'SpotLight' library, i am getting above issue .. Kindly help..

org.gradle.execution.MultipleBuildFailures: Build completed with 1 failures.
AAPT: error: duplicate value for resource 'attr/fontStyle' with config ''.
AAPT: error: resource previously defined here.

**Comment by TakuSemba** [comment]
I can take a look if you could give me a sample code that I can reproduce.

**Comment by TakuSemba** [comment]
I'm closing this due to the lack of information.
