### ISSUE TITLE
Draw Spotlight over activity, not DecorView

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [TakuSemba/Spotlight#79]
This probably isn't functionality wanted by many, so i made a fork which draws the spotlight overlay within the root view instead of the DecorView which means your custom target views don't have to worry about whether the nav buttons / app bar exists

This was useful for me, so it might be useful for others...

https://github.com/OliverCulleyDeLange/Spotlight
  `  implementation 'com.github.OliverCulleyDeLange:Spotlight:05480906cc'`

Putting this as an issue here so people have a chance of finding it.

**Comment by TakuSemba** [comment]
Thank you for sharing this. 
I really appreciate your idea and might reimplement in your suggested way.

**Comment by TakuSemba** [comment]
I added functionality to set a container of Spotlight as of the version of 2.0.0.
So, please check it out!
