### ISSUE TITLE
Hard to implement for Views in Fragment.

### ISSUE THREAD

**Issue by RahulBhavani** [TakuSemba/Spotlight#85]
Hi,
Thank you for creating this awesome library.
I had hard time getting this work for Views in Fragment. The main problem in using with Views in Fragment is that we can't get View's height/width straight forwardly. 
Do you have any sample which illustrate usage of this library for Fragment?

**Comment by TakuSemba** [comment]
Hi, I added a sample on the demo app.
Please check it out.
