### ISSUE TITLE
Can i use this library inside my paid app?

### ISSUE THREAD

**Issue by cybersa** [TakuSemba/Spotlight#86]
I'm a indie developer and planning to use this library inside my paid app. But i'm not sure whether can i or not since it uses Apache 2 license. Can you help me things needs to be do? Is it enough to include Library name with link and license name in the about menu of application.  I'm new to license terms, i searched google for answer but i didn't get concrete answer. Thats why I'm posting here.

**Comment by NotNotMarshall** [comment]
Yes.. enjoy. and always remember that All you need is love

**Comment by TakuSemba** [comment]
You can see what you can do from this link. 
https://choosealicense.com/licenses/apache-2.0/

Yes, you can use this in your project. 👍
