### ISSUE TITLE
would you please share java demo code (not kt)

### ISSUE THREAD

**Issue by waqarr** [TakuSemba/Spotlight#87]
would you please share java sample code  (not kt) with new version thank you so much

**Comment by TakuSemba** [comment]
@waqarr 
Hi, is there any problems when using from java code?

**Comment by VarunSaini23** [comment]
@TakuSemba Where can i find java implementation of this library. My app is in java and i want to use this library.

**Comment by TakuSemba** [comment]
You can use this library from Java code. 
Do you have an error when using this library from Java code?

**Comment by yousefYEelsayed** [comment]
I cant Spotlight.Builder(this) in java

**Comment by doneill** [comment]
The library doesn't provide overloaded constructors for shapes so Java cannot create a `Circle` in the same way as existing kotlin sample which can lead to errors.  This could be an enhancement request on it's own but relevant to requesting a Java sample as well.

**Comment by TakuSemba** [comment]
@doneill 

Sorry for the late replay.
That's definitely what I should fix.
I will provide overloaded constructors for `Shape` and `Effect` on the next version, which will be released soon.

**Comment by TakuSemba** [comment]
I fixed Shape and Effect constructors on v2.0.2.
