### ISSUE TITLE
Using this in a recyclerView

### ISSUE THREAD

**Issue by ranjitzade** [TakuSemba/Spotlight#88]
How to use this lib in a RecyclerView?
How to show on particular views inside recyclerview items?

**Comment by nyamwaya** [comment]
It's not clear to me either, very little support on this issue still love it though.

**Comment by muhammaduzaer** [comment]
> How to use this lib in a RecyclerView? How to show on particular views inside recyclerview items?

got the item of recycler view with this. 

recyclerView.findViewHolderForAdapterPosition(position).itemView
