### ISSUE TITLE
NavigationDrawer Fragments

### ISSUE THREAD

**Issue by dadou181295** [TakuSemba/Spotlight#90]
Hello sir, thanks your your library.

I've been working days I can't understand I have. a navigation drawer with Main Activity hosts Fragments I want to show the stuff in fragment A, where should I create the instance ?
in Main ? or in the fragment ...
also there is .setContainer ()
I'm very confused.. please can you tell me a simple example ?

thanks you

**Comment by dadou181295** [comment]
![Capture d’écran 2020-06-18 à 11 46 39](https://user-images.githubusercontent.com/54495807/84999179-7b79b180-b159-11ea-9cc6-31bb80b98aef.png)

Please help ... :(

**Comment by kairliyev** [comment]
Do it in Fragment class

`private fun showSpotlight() {
        val view = this.view?.findViewById<ImageView>(R.id.button) // target view ( Icons, TextViews etc )
        view?.post { 
            val location = IntArray(2) // getting target size
            view.getLocationInWindow(location)
            val x = location[0] + view.width / 2f
            val y = location[1] + view.height / 2f

            val firstRoot = FrameLayout(this.requireContext())
            val first = layoutInflater.inflate(R.layout.layout_target, firstRoot) // its transparent background with text
            val firstTarget = Target.Builder()
                .setAnchor(x, y) // set x,y of target view
                .setShape(Circle(75f))
                .setOverlay(first)
                .build()

            targets.add(firstTarget)

            val spot = Spotlight.Builder(this.requireActivity())
                .setTargets(firstTarget)
                .setBackgroundColor(R.color.spotlightBackground)
                .setAnimation(DecelerateInterpolator(2f))
                .build()
            spot.start()

            first.setOnClickListener {
                spot.finish() //close spotlight by finish()
            }
        }
    }`
Good luck:)

**Comment by TakuSemba** [comment]
Did you figure it out?
As kairliyev said, I think it works if you do it in Fragment.

please reopen this, if there is still a problem.
I'm happy to help you.
