### ISSUE TITLE
Displaying spotLight over Dialog

### ISSUE THREAD

**Issue by NaveenKadiyala** [TakuSemba/Spotlight#95]
Hi, the library was cool and working fine in activities and fragments.
But whenever i want to display the overlay on top of dialog it was displaying below the dialog.
Please suggest any possible solution..

**Comment by TakuSemba** [comment]
To make it clear, you want Spotlight only on a Dialog or on the entire screen while displaying a dialog?

If it's former, you can just use `Spotlight.Builder.setContainer()` and set dialog view in it. If it's latter, it's pretty difficult to archive it since the view where Spotlight is drawn is under the dialog.

**Comment by Albul** [comment]
It is possible, no changes required. Just use `setContainer` and set root view of dialog.
Let me show an example:
```
fun showTutorial(
    activity: AppCompatActivity,
    @IdRes idToHighlight: Int,
    dialogTag: String? = null
) {
    val rootView: ViewGroup = if (dialogTag == null) {
        activity
            .findViewById<ViewGroup?>(android.R.id.content)
            ?: return
    } else {
        (activity.supportFragmentManager
            .findFragmentByTag(dialogTag) as? DialogFragment)
            ?.dialog
            ?.window
            ?.findViewById<ViewGroup?>(android.R.id.content)
            ?: return
    }
    val targetView: View = rootView.findViewById<View>(idToHighlight) ?: return
    val tutorialView: View = activity.layoutInflater
        .inflate(R.layout.your_tutorial_view, rootView, false)
    
    val spotlight = Spotlight.Builder(activity)
        .setTargets(
            Target.Builder()
                .setAnchor(targetView)
                .setOverlay(tutorialView)
                .build()
        )
        .setContainer(rootView)
        .build()
}
```

**Comment by TakuSemba** [comment]
@Albul 
Thank you for sharing your solution.

@NaveenKadiyala
Could you check if that solves your problem?

**Comment by NaveenKadiyala** [comment]
Sorry for the delay, I just found out this answer!!
I have left that project long back, so couldn't checkout the @Albul answer..
So closing this issue as resolved based on the Albul answer..
Thank you @Albul @TakuSemba
