### ISSUE TITLE
Cannot add a null child view to a ViewGroup

### ISSUE THREAD

**Issue by solution888** [TakuSemba/Spotlight#96]
What is wrong?
```
        val targets = ArrayList<Target>()
        val target = Target.Builder()
                .setAnchor(binding.customview)
                .setShape(Circle(200f))
                .setOnTargetListener(object : OnTargetListener {
                    override fun onStarted() {

                    }

                    override fun onEnded() {

                    }
                })
                .build()
        targets.add(target)

        val spotLight = Spotlight.Builder(requireActivity())
                .setTargets(targets)
                .setBackgroundColor(R.color.background)
                .setDuration(1000L)
                .setAnimation(DecelerateInterpolator(2f))
                .setOnSpotlightListener(object : OnSpotlightListener {
                    override fun onStarted() {

                    }

                    override fun onEnded() {

                    }
                })
                .build()

        spotLight.start()
```

**Comment by solution888** [comment]
I didn't set targets before.
So I will close this issue.

**Comment by borjaruiz** [comment]
I'm having the same problem, tried many things without success. I'm using java.
myView is found using Butterknife, and if I put a breackpoint before starting spotlight, it's not null

private List<Target> getTargets() {
        List<Target> targets = new ArrayList<>();
        targets.add(new Target.Builder().setAnchor(myView).setShape(new Circle(100f)).build());
        return targets;
    }

@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        new Spotlight.Builder(getActivity()).setTargets(getTargets()).build().start;
    }
